# wskdeploy manifest file

packages:
  default:
    version: 1.0
    license: Apache-2.0
    actions:
      helloJava:
        function: hello-world-java.jar
        runtime: java
        main: com.example.FunctionApp
      webHello:
        function: hello-world-java.jar
        runtime: java
        main: com.example.WebHello      
        web-export: true
  golden-ratio:
    actions:
      fibonacciNumber:
        function: hello-world-java.jar
        runtime: java
        main: com.example.FibonacciNumber
      calculateRatio:
        function: hello-world-java.jar
        runtime: java
        main: com.example.CalculateRatio
      calculateRatioWeb:
        function: hello-world-java.jar
        runtime: java
        main: com.example.CalculateRatioWeb
      cloudantDocBuilder:
        function: hello-world-java.jar
        runtime: java
        main: com.example.BuildCloudantDoc  
      readCloudantDoc:
        function: hello-world-java.jar
        runtime: java
        main: com.example.ReadCloudantDoc 
    sequences:
      ratio:
        actions: fibonacciNumber, calculateRatio, cloudantDocBuilder, go-serverless-cloudant/write
        web: true
      ratioWeb:
        actions: fibonacciNumber, calculateRatioWeb
        web: true
    apis:
      ratioAPI: #Endpoint ID
        api: #API Basepath
          ratio: #Endpoint Path
            ratio: #Function Reference
              method: GET
              response: json  
    triggers:
      fibonacciAdd:
        feed: /[YOURACCOUNTNAME]_dev/go-serverless-cloudant/changes
        inputs: 
          dbname: fibonaccidb
          lifecycleEvent: CREATE
    rules:
      readFibonacciRatios:
        trigger: fibonacciAdd
        action: readCloudantDoc
